### ISSUE TITLE
FAQ: What does category: null mean in pypistats python_minor?

### ISSUE THREAD

**Issue by cclauss** [hugovk/pypistats#100]
What does `category: null` mean in `pypistats python_minor`?

% __pypistats python_minor tap2junit__
| category | percent | downloads |
|----------|--------:|----------:|
| null     |  56.85% |       365 |

**Comment by cclauss** [comment]
Cool.  Thanks.  Have you ever thought about using https://mybinder.org to add a `launch Binder` button to `README.md` that allows visitors to directly run pypistats?  I have been experimenting with it at https://github.com/cclauss/library-of-congress-classifier-hack/blob/master/README.md

**Comment by hugovk** [comment]
I've heard of it but not used it. I think between this tool and the online https://pypistats.org it might not be as useful as for other tools, but thanks for the suggestion!
