### ISSUE TITLE
Wheel statistics

### ISSUE THREAD

**Issue by tuukka** [hugovk/pypistats#245]
Would it be possible to display source and wheel statistics separately?

**Comment by hugovk** [comment]
Hi! Not right now. This project is a client for the API at https://pypistats.org/api/ = https://github.com/crflynn/pypistats.org which doesn't have that sort of data available. You could ask there?

That project gets data from PyPI's Google BigQuery.

https://github.com/ofek/pypinfo is another project to query the BigQuery more directly. You need to set up some Google credentials and get monthly free quota. Having said that, I don't think pypinfo exposes sdist/wheel stats separately, so you'd probably need to query BigQuery directly.

More info:

* https://packaging.python.org/guides/analyzing-pypi-package-downloads/

I clicked through to the schema and it does save the filename. For example:

```
SELECT file.filename FROM `bigquery-public-data.pypi.file_downloads` WHERE DATE(timestamp) = "2021-05-17" LIMIT 10
```

Row | filename |  
-- | -- | --
1 | boto3-1.17.59-py2.py3-none-any.whl |  
2 | wheel-0.9-py27-none-any.whl |  
3 | tr0nz0d-0.0.3.tar.gz |  
4 | argcomplete-1.12.3-py2.py3-none-any.whl |  
5 | Flask-2.0.0-py3-none-any.whl |  
6 | kafka_python-2.0.2-py2.py3-none-any.whl |  
7 | cramjam-2.3.1-cp39-cp39-manylinux1_x86_64.whl |  
8 | tensorflow_text_nightly-2.6.0.dev20210516-cp36-cp36m-macosx_10_9_x86_64.whl |  
9 | wheel-0.29.0-py2.py3-none-any.whl |  
10 | pip-19.0-py2.py3-none-any.whl |

**Comment by tuukka** [comment]
Thank you for the helpful information! I looked too quickly and was confused between pypistats and pypistats.org first. There's now a new issue at https://github.com/crflynn/pypistats.org/issues/37

**Comment by hugovk** [comment]
Closing this as it's not available via the API, but can re-open if it's added in the future 👍
