### ISSUE TITLE
Pypistats broken? Sudden statistics crash across all projects

### ISSUE THREAD

**Issue by arcivanov** [hugovk/pypistats#299]
Sorry for leaving the issue here - there seems to be no site-related tracker I could find.

This data is implausible:

![image](https://user-images.githubusercontent.com/5355666/144763490-4c4050c4-d066-462c-aa55-a9ca46532ac9.png)

![image](https://user-images.githubusercontent.com/5355666/144763504-cd7c99b9-bca9-4aef-8bef-f9c2276e6a2e.png)

![image](https://user-images.githubusercontent.com/5355666/144763527-9b0bde09-90ef-4b7a-8fcf-8bab661b01f5.png)

All projects from small to large are affected.

Was there change in analytics?

**Comment by hugovk** [comment]
Hi, it's this:

* https://status.python.org/incidents/2jj696st6yn5

Hopefully it'll be sorted in a few days. 

Related:

* https://github.com/pypa/linehaul-cloud-function/issues/54
* https://github.com/crflynn/pypistats.org/issues/44

**Comment by arcivanov** [comment]
Thank you!
