### ISSUE TITLE
broken links to Google BigQuery

### ISSUE THREAD

**Issue by milahu** [hugovk/pypistats#319]
these pages have broken links to Google BigQuery

* https://pypistats.org/about
* https://pypistats.org/api/

working links

* https://console.cloud.google.com/search;q=bigquery-public-data:pypi
* https://console.cloud.google.com/marketplace/product/gcp-public-data-pypi/pypi

example SQL code

https://stackoverflow.com/a/71414912/10440128

moved from https://github.com/pypa/warehouse/issues/10900

**Comment by hugovk** [comment]
Hi, thanks for the report! 

This is the repo for the CLI tool, please could you report it at the website repo?

-> https://github.com/crflynn/pypistats.org

Thank you!
