### ISSUE TITLE
API to access data of last 6 months

### ISSUE THREAD

**Issue by drdhaval2785** [hugovk/pypistats#36]
As mentioned in documentation, timeline data is retained for 180 days.
But currently I did not find a way to see how the package fared in last 6 month let's say. It gives last day, week and month.

I would love to see a functionality which can give monthly downloads for past 6 months.

**Comment by hugovk** [comment]
The `overall` subcommand would give you that. (Although, right now, https://pypistats.org/api/ is returning `503 Server Error: SERVICE UNAVAILABLE`.)

An [example from the tests](https://github.com/hugovk/pypistats/blob/2b1148a65ec17d599d26a88880d501e98c99e429/tests/test_pypistats.py#L466-L490), `pypistats overall pip --mirrors without`, would give something like this (but with a **much bigger** number (~366m?)):

|    category     | downloads |
|-----------------|----------:|
| without_mirrors | 2,297,591 |

**Comment by drdhaval2785** [comment]
Thanks @hugovk.
Let me clarify what I wanted and what most package uploaders would want.

last month - 56
second last month - 55
third last month - 50
fourth last month - 102
fifth last month - 90
sixth last month - 30

Something like this for week and day can also be thought of.

If you can give finer control like 'startdate' and 'enddate', it would be most sought after.

**Comment by hugovk** [comment]
Please could you have a look at PR  #38?

And there's already `-start-date yyyy-mm-dd` and `--end-date yyyy-mm-dd` for most subcommands.

**Comment by drdhaval2785** [comment]
Looks good to me looking at the results. Thanks for the pains.
