### ISSUE TITLE
`rich` format option is not implemented but included!

### ISSUE THREAD

**Issue by lnxpy** [hugovk/pypistats#399]
Since the `rich` option for `--format` is not implemented yet, wouldn't it be better if you (permanently) remove the `rich` item from `FORMATS` [here](https://github.com/hugovk/pypistats/blob/3150dd940d21737884de4074bff84b95171aa18e/src/pypistats/cli.py#L121) in a hotfix? It's actually causing `KeyError`. I looked over `pytablewriter` and they don't seem to be supporting `rich` at all. Like they've never even had the rich integration. You can use [`rich.table.Table`](https://rich.readthedocs.io/en/stable/reference/table.html?highlight=rich.table.Table#rich.table.Table) though.

Thank you for maintaining this amazing package! :)

**Comment by hugovk** [comment]
Well spotted, that should be removed. Would you like to create a PR? The README also needs updating.

Glad you find this useful!

**Comment by lnxpy** [comment]
Sure. I'm on it.
