### ISSUE TITLE
`IndexError` while using the arguments with unavailable option values

### ISSUE THREAD

**Issue by lnxpy** [hugovk/pypistats#401]
When using any of the `python_major`, `python_minor`, and `system` positional arguments with an invalid value for their option, it raises `IndexError` and the exception should be handled properly IMO.

For example, see the following results.

```sh
$ pypistats python_minor pillow -V 3.0
...
    first = data[0]["date"]
            ~~~~^^^
IndexError: list index out of range
$
```

```sh
$ pypistats python_major pillow
┌──────────┬─────────┬─────────────┐
│ category │ percent │   downloads │
├──────────┼─────────┼─────────────┤
│ 3        │  93.48% │ 303,004,748 │    ---> v4 is not available
│ null     │   4.90% │  15,894,348 │
│ 2        │   1.62% │   5,247,610 │
│ Total    │         │ 324,146,706 │
└──────────┴─────────┴─────────────┘

Date range: 2023-01-16 - 2023-07-15

$ pypistats python_major pillow -V 4    ---> when we ask for it
...
    first = data[0]["date"]
            ~~~~^^^
IndexError: list index out of range
$
```

```sh
$ pypistats system pillow -o bsd
...
    first = data[0]["date"]
            ~~~~^^^
IndexError: list index out of range
$
```

**Comment by lnxpy** [comment]
If you consider this issue as a bug, I can fix it as well. :)

**Comment by hugovk** [comment]
Ah yes, we can definitely handle this in a nicer way.

For the first, we could consider the value `4` is potentially valid, but there's no data for it (yet, if ever!).

For example, using the `--verbose` flag, here's the API endpoint for the first one:

https://pypistats.org/api/packages/pillow/python_major?&version=4

```json
{
"data": [],
"package": "pillow",
"type": "system_downloads"
}
```


And for the second, there could potentially be a `bsd` input, the docs give "`windows`, `linux`, `darwin` or `other`" as examples, not the full set:

https://pypistats.org/api/#api-packages-package-system

https://pypistats.org/api/packages/pillow/system?&os=bsd

```json
{
"data": [],
"package": "pillow",
"type": "system_downloads"
}
```

---

There are a couple of ways to fix this. We could validate input, and only allow `2` or `3`, or `windows`, `linux`, `darwin` or `other` as input. But as mentioned, other values could potentially be valid.

The other would be to better handle the case where there's no data.

I've seen this come up before for other queries, for example when a package is new and there's no downloads yet been recorded for it (and some other cases I don't recall).

---

For the CLI, we can handle this more gracefully and should still exit with a non-zero return code.

For the library API (https://github.com/hugovk/pypistats#example-programmatic-use), should we still raise some sort of exception or return something else?

**Comment by lnxpy** [comment]
> There are a couple of ways to fix this. We could validate input, and only allow 2 or 3, or windows, linux, darwin or other...

I feel like validating might not be the one. Some day, they may decide to drop Python 4.0. Who knows? And that moment, we need to drop an update and add the version to `choices`. That "(yet, if ever!)" got me btw. 😄 

We can handle this in a way where the `data=[]` as you mentioned. It does exit with a non-zero code at the moment but it's been terminated by the interpreter not manually with more details.

I think if we store the custom exceptions and raise them when we need to, that might do the trick. That'll be practical in both CLI and programmatic ways.

**Comment by hugovk** [comment]
Sounds good, would you like to put a PR together and we can go from there?

**Comment by lnxpy** [comment]
Sure.

**Comment by lnxpy** [comment]
@hugovk have you seen the result of this one?!

```sh
pypistats python_major requests -V 4
```

**Comment by hugovk** [comment]
Haha! 

Yeah, I think there was a custom build of Python using 4.0 to see how things worked with the bump :)

See https://pypi.org/project/flake8-2020/ for some common gotchas.

Also someone has done ones with 3.60, pi, 4.11, 5.0 and 1.337!

https://hugovk.github.io/pypi-tools/

**Comment by lnxpy** [comment]
✅  Part of this issue has been fixed in #402

**Comment by hugovk** [comment]
Anything left to do here, or does #402 cover the important parts?

**Comment by lnxpy** [comment]
We're done with this issue. I witnessed some other issues. They were as critical as I decided not to use `pypistats` and create my own API interface instead!!

**Comment by hugovk** [comment]
Oh, exciting!

https://github.com/lnxpy/pypi-stats-viewer
https://github.com/lnxpy/hey#package-stats

**Comment by lnxpy** [comment]
@hugovk Its issues were not that big of a deal on `pypi-stats-viewer` as it's an experimental project. I created my own API interface on a more serious codebase [here](https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/integrations/handlers/pypi_handler/api.py).

I'll open another issue and explain the problems. ✌🏻
