### ISSUE TITLE
Improper IndexError handling

### ISSUE THREAD

**Issue by Yao-Wen-Chang** [hugovk/pypistats#437]
`File "/home/..../lib/python3.11/site-packages/pypistats/__init__.py", line 261, in _date_range
    first = data[0]["date"]
            ~~~~^^^
IndexError: list index out of range`

The exception does not handle the data list is empty.
The error will cause the program to stop without proper handling.

**Comment by hugovk** [comment]
Please could give an example of how to reproduce this?

**Comment by Yao-Wen-Chang** [comment]
> Please could you give an example of how to reproduce this?

Scanning the package that is distributed today.
For example, using this command `pypistats python_major -j testbrojct`.

**Comment by hugovk** [comment]
Thanks, so this is for a project which doesn't exist on PyPI. It makes sense to handle this better. I'll add some comments to the PR.

**Comment by Yao-Wen-Chang** [comment]
Ohhh... I did not realize I provided the wrong package lol.
But, this is indeed a small bug.
