### ISSUE TITLE
PyPI Infra Incident Impacting BigQuery dataset

### ISSUE THREAD

**Issue by ewdurbin** [hugovk/pypistats#441]
Hello! We are tracking an incident that impacted (is impacting?) the BigQuery data sets.

It is evident in the dropoff of stats over the last week. We are currently working to backfill the data, so your stats may need to similarly be backfilled.

I'll leave this issue open for now and notify when we believe we have caught up.

**Comment by tmas-definitive** [comment]
I am seeing similar results in the API calls - the overall downloads for pypi stats have fallen drastically (https://pypistats.org/packages/__all__)

Looking forward to a resolution - will backfill our data from an API once there is a response from the team.

**Comment by hugovk** [comment]
Thanks for the heads up!

This repo is a CLI wrapping the API of https://github.com/crflynn/pypistats.org, so they'll need to backfill. I linked from https://github.com/crflynn/pypistats.org/issues/67 to here.

**Comment by ewdurbin** [comment]
Ope, sorry. It's not super discoverable from the site. I'll move this issue there and back-link.
