### ISSUE TITLE
dependencies listed multiple times

### ISSUE THREAD

**Issue by nschloe** [hugovk/pypistats#56]
If a dependency is listed more than once in `install_requires` or `extra_requires` (which is perfectly possible), e.g.,
```python
    install_requires=["numpy"],
    extras_require={
        "all": ["netCDF4", "h5py", "lxml"],
        "exodus": ["netCDF4"],
        "hdf5": ["h5py"],
        "xml": ["lxml"],
    },
```
then it is listed multiple times in the web interface too, where it makes less sense:
![m](https://user-images.githubusercontent.com/181628/55541873-270a2380-56c6-11e9-9dbf-9f8e2b8025a6.png)
Perhaps this can be `unique`d.

Perhaps optional (`extra`) dependencies could be listed as such in the web interface, too.

**Comment by hugovk** [comment]
Thanks for the report, but this repo is just for the pypistats client. Please can you report this to the pypistats website? 

https://github.com/crflynn/pypistats.org

**Comment by nschloe** [comment]
https://github.com/crflynn/pypistats.org/issues/17
