### ISSUE TITLE
Yearly downloads?

### ISSUE THREAD

**Issue by Ruturaj4** [hugovk/pypistats#60]
I  checked the online api. But, I haven't find any endpoint which gives total or total yearly download counts. Is there any option to do that?

**Comment by hugovk** [comment]
Unfortunately not with pypistats (this command-line tool) or https://pypistats.org/ the website: only 6 months of data is available.

However, you can get 12 months, and more, of data using https://github.com/ofek/pypinfo. It takes a bit more effort to get the BigQuery set up, but it's not too tricky.

Also, json2csv.py in https://github.com/hugovk/pypi-tools is a wrapper around pypinfo to get stats for a longer timeframe.
