### ISSUE TITLE
couldn't download pypistats with pip

### ISSUE THREAD

**Issue by JacksonWuxs** [hugovk/pypistats#71]
`No matching distribution found for DataProperty<1.0.0,>=0.43.1 (from pytablewriter[html]>=0.41.2->pypistats)`

**Comment by hugovk** [comment]
What Python version are you using?

**Comment by hugovk** [comment]
And what do you get for `pip freeze | grep pytablewriter`?

**Comment by JacksonWuxs** [comment]
Well, OK, when I rerun the command, it works~
