### ISSUE TITLE
Fail to have the data more than half year

### ISSUE THREAD

**Issue by zhangguanheng66** [hugovk/pypistats#85]
It seems the download numbers are not available for the timeline more than half year.
```
pypistats python_major torchtext --start-date 2019-06-01 --end-date 2019-06-30
```

returned:
```
| category | downloads |
|----------|----------:|
| Total    |         0 |

Date range: 2019-06-01 - 2019-06-30
```

**Comment by hugovk** [comment]
That's right, the API used only has 6 months' data:

* https://pypistats.org/about#data

For data back to January 2016, you can use https://github.com/ofek/pypinfo, and will need to sign up for an API key. You get free quota too, but might not be able to get the full output in a single month. 

See https://github.com/hugovk/pypi-tools for some tools that can help.

I'll update the README and possibly add a warning to code.

**Comment by zhangguanheng66** [comment]
Why cannot we have all the data via `pypistats`, instead of just six months?

**Comment by hugovk** [comment]
> PyPI Stats attempts to operate within the free tier of its hosted services. For this reason, aggregate data is only retained for 180 days.

**Comment by hugovk** [comment]
Please see PR https://github.com/hugovk/pypistats/pull/86.
